### ISSUE TITLE
mandatory checkboxes 

### ISSUE THREAD

**Issue by michael-johnstone** [cisr-du/qts#1]
cannot make checkboxes mandatory

**Comment by ghost** [comment]
I need the ability (a standardised ability) to force the checkbox control to be mandatory an example form I'm planning to implement is below. All checksboxes are to be mandatory in the below example. I can currently workaround this by making the defect control mandatory.

![mandatory_checkboxes_on_form](https://cloud.githubusercontent.com/assets/9923249/5160403/88bce14a-73df-11e4-8dc0-75afea0a908f.jpg)

**Comment by michael-johnstone** [comment]
do you want the record to save only once all mandatory checkboxes are checked by the user?
more generically, a mandatory checkbox will only save when its value is changed from its default value?

**Comment by ghost** [comment]
The mandatory checkboxes should operate as per other mandatory fields; as I understand the current operation of mandatory fields is to save data only when the complete record is saved (as would be true in the above instance). The ability to save per row in a form (as we have discussed) I consider separate functionality.

**Comment by ghost** [comment]
Fixed in 2.2.2
