### ISSUE TITLE
[Import] Import error Microsoft.Jet.OLEDB.4.0 not registered

### ISSUE THREAD

**Issue by ghost** [cisr-du/qts#17]
Attempting to import data from MSExcel into the Stamp table has failed. We see a recurrence of the issue from ~July 2014 with system registration of Microsoft.Jet.OLEDB.4.0.

![image](https://cloud.githubusercontent.com/assets/9923249/5222242/f00e7e06-76e3-11e4-9160-4ac1003c8ce3.png)

**Comment by ghost** [comment]
Problem exists for complete import function throughout the entire application currently for MS Access, MS Excel, MS Query. Cannot update data for testing next week.

**Comment by burhan-khan** [comment]
This problem is raised due to the conflict of 32-bit and 64-bit setups. The version 2.0.5 found on the link below is a 32-bit. Can you please confirm if import works this time?

**Comment by ghost** [comment]
A 32bit compile creates a functional build. We need to consider a permanent solution if the plan is to offer 64bit compiles moving forward or force the compiler to 32bit everytime.
