### ISSUE TITLE
[Mapping] Mapping multiple items to a test results in incorrectly 'inherited' departments

### ISSUE THREAD

**Issue by ghost** [cisr-du/qts#21]
When adding a new mapping containing multiple items where an item exists in a previous mapping, the system will add the existing test to the 'selected tests' dialog. 

Saving this scenario will add all items will to the other selected test.

Unselecting the automatically added test prior to saving will remove the existing item from this existing test which is not the required behavior.

**Comment by ghost** [comment]
I can workaround this by manually re-selecting the incorrectly mapped items and deselecting the incorrect test post mapping.

**Comment by burhan-khan** [comment]
Hi Wayne, I have emailed you the link of the video to confirm if this is not the kind of behaviour you expect.

**Comment by ghost** [comment]
Yes this demonstration seems to work as expected now, thanks
