### ISSUE TITLE
[FIXED][2.2.2][Mapping] Not all records show up in mapped dropdown

### ISSUE THREAD

**Issue by ghost** [cisr-du/qts#34]
Version 2.1.0, not all mapped data is showing up in dropdowns

![image](https://cloud.githubusercontent.com/assets/9923249/6495558/7ea8407a-c31f-11e4-8444-c84249f005e9.png)

![image](https://cloud.githubusercontent.com/assets/9923249/6495577/93f6f390-c31f-11e4-90e3-f9e6d0d5a38b.png)

Mapped is turned on in option for dropdown

**Comment by burhan-khan** [comment]
This issue has been resolved now. Thanks.

**Comment by ghost** [comment]
Existing maps exhibiting same reported failure
New Maps are not working at all currently on locally upgraded db

**Comment by ghost** [comment]
Fixed in 2.2.2
