### ISSUE TITLE
[Form Builder] Labels have inconsistent names

### ISSUE THREAD

**Issue by michael-johnstone** [cisr-du/qts#8]
![image](https://cloud.githubusercontent.com/assets/9736620/5194870/26092588-7568-11e4-8b2f-2b6b056b72cc.png)

'Label' from toolbar is type TextBlock

**Comment by michael-johnstone** [comment]
![image](https://cloud.githubusercontent.com/assets/9736620/5194887/4e211878-7568-11e4-9e60-e6842bf9b86b.png)

'Label' from context menu is type CustomLabel

**Comment by ghost** [comment]
The properties of each are different, these appear to be different objects not just different names.

![image](https://cloud.githubusercontent.com/assets/9923249/5276233/e33f2b34-7b08-11e4-8ac2-8be97a499afa.png)

![image](https://cloud.githubusercontent.com/assets/9923249/5276235/ed00560c-7b08-11e4-8560-8b1e904bea24.png)

**Comment by burhan-khan** [comment]
I am unable to recreate "CustomLabelProperties" in a new test. However, I do find them in the existing tests. Please explain steps involved to reproduce this bug.

**Comment by ghost** [comment]
Add a label using the context menu (right click menu), _DO NOT_ use the toolbar label option.

Resulting control type will be "CustomLabel"

![image](https://cloud.githubusercontent.com/assets/9923249/5444483/ffb492c2-84fe-11e4-9a35-de5641375cf3.png)

**Comment by burhan-khan** [comment]
This issue has been resolved now. Thanks for your help.

**Comment by ghost** [comment]
What will be the effect on existing forms in the next upgrade? Will the labels be converted automatically retaining like for like properties or will we have to rebuild any effected forms?

New forms we built once noticing this issue have been built with "TextBlock" type, what is the final format?

**Comment by burhan-khan** [comment]
You will not be required to rebuild any effected forms. I will convert existing controls in the forms to the new type. "TextBlock" type is the final format that is better than the previous implementation.

**Comment by ghost** [comment]
Thanks burhan, I look forward to the new release

**Comment by burhan-khan** [comment]
![image](https://cloud.githubusercontent.com/assets/9795137/5467138/11935ff4-860e-11e4-8663-fd07f84113b4.png)

![image](https://cloud.githubusercontent.com/assets/9795137/5467133/08a1642c-860e-11e4-9bd7-c7cc84a13bfc.png)

**Comment by ghost** [comment]
Fixed
